# Generated by Django 5.1.7 on 2025-04-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile_pic.png', null=True, upload_to='profile_pics/'),
        ),
    ]
