# Generated by Django 5.1.7 on 2025-04-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('mountain', 'Mountain'), ('city', 'City'), ('electric', 'Electric'), ('road', 'Road'), ('hybrid', 'Hybrid')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bike_image/')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('quantitiy_in_stock', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
