# Generated by Django 5.1.7 on 2025-04-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_rename_bike_bikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
