# Generated by Django 5.1.7 on 2025-04-19 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_bikes_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikes',
            old_name='quantitiy_in_stock',
            new_name='quantiy_in_stock',
        ),
    ]
