# Generated by Django 5.1.7 on 2025-04-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_rename_quantitiy_in_stock_bikes_quantiy_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikes',
            old_name='quantiy_in_stock',
            new_name='quantity',
        ),
    ]
