# Generated by Django 5.1.7 on 2025-05-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_rename_quantiy_in_stock_bikes_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='latitude',
            field=models.FloatField(default=80),
        ),
        migrations.AddField(
            model_name='bikes',
            name='longitude',
            field=models.FloatField(default=80),
        ),
    ]
