# Generated by Django 5.1.7 on 2025-05-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0007_bikes_latitude_bikes_longitude 2'),
        ('bikes', '0007_bikes_latitude_bikes_longitude'),
    ]

    operations = [
    ]
