# Generated by Django 5.1.7 on 2025-05-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_bikerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
