# Generated by Django 5.1.7 on 2025-05-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0009_bikes_image_2_bikes_image_3_bikes_image_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
