# Generated by Django 5.1.7 on 2025-05-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_merge_20250507_1555'),
        ('bikes', '0010_alter_bikes_rating'),
    ]

    operations = [
    ]
