# Generated by Django 5.1.7 on 2025-05-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0011_merge_20250508_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikes',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='bikes',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='bikes',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='bikes',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='bikes',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
